name: CI

on:
  push:
    branches: [ main ]  # Adjust the branch name if different
  pull_request:
    branches: [ main ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Test against multiple Node.js versions

    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Caches npm dependencies

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run type-check
      - name: Run TypeScript type-check
        run: npm run type-check
